- name: check phalcon version
  shell: php -i | grep Phalcon
  register: current_phalcon_extension
  ignore_errors: True

- name: Add Phalcon PHP Framework PPA repository
  apt_repository: repo='ppa:phalcon/stable'
  tags: phalcon
  when: current_phalcon_extension | failed

- name: Update APT cache
  apt: update_cache=true
  tags: phalcon
  when: current_phalcon_extension | failed

- name: Install Phalcon PHP Framework
  apt: pkg=php5-phalcon state=installed
  tags: phalcon
  notify: restart webserver
  when: current_phalcon_extension | failed